config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'
  root 'pages#home'
  resources :movies do
    resources :screenings, only: [:show]
  end

  resources :screenings do
    resources :reservations, only: %i[new create]
  end
  resources :reservations, only: %i[index show update destroy]

  get '/user', to: 'users#show'

  post 'screenings/:screening_id/reservations/offline', to: 'reservations#create_at_desk', as: 'offline_reservation'

  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
      resources :movies, only: %i[index show]

      resources :screenings, only: %i[show] do
        resources :reservations, only: %i[create]

        post '/reservations', to: 'reservations#create'
      end
      resources :reservations, only: %i[show]
    end
  end
end

app/models/screening.rb
class Screening < ApplicationRecord
  acts_as_paranoid
  belongs_to :movie
  belongs_to :hall
  has_many :reservations
  validates :end_time, comparison: { greater_than: :start_time }, presence: true
  validates :start_time, comparison: { greater_than: Time.current }, presence: true
  before_validation :calculate_end_time

  def movie
    Movie.with_deleted.find(movie_id)
  end

  def available_seats
    taken_seats = reservations.joins(:tickets).where.not(status: :cancelled).pluck(:'tickets.seat')
    hall.seats - taken_seats.flatten
  end

  def calculate_end_time
    self.end_time = start_time + ADS_DURATION + movie.duration.minutes if start_time.present?
  end

  after_destroy do
    CancelAllReservationsJob.perform_later(id)
  end
end

app/controllers/api/v1/screenings_controller.rb
module Api
  module V1
    class ScreeningsController < ApiController
      def show
        @screening = Screening.find(params[:id])
        render json: ScreeningSerializer.new(@screening, include: %i[movie hall], fields: {
                                               movie: %i[title duration],
                                               hall: [:name]
                                             })
      end
    end
  end
end

app/controllers/screenings_controller.rb
class ScreeningsController < ApplicationController
  include Pundit::Authorization
  before_action :authenticate_user!, except: %i[show index]
  def show
    set_screening
    authorize @screening
  end

  def index
    authorize Screening
    render :index, locals: { movies: Movie.includes(:screenings) }
  end

  def new
    authorize Screening
    @screening = Screening.new
  end

  def edit
    set_screening
    authorize @screening
  end

  def create
    @screening = Screening.new(screening_params)
    authorize @screening
    if @screening.save
      redirect_to screenings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    set_screening
    authorize @screening
    if @screening.update(screening_params)
      redirect_to screenings_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    set_screening
    authorize @screening
    @screening.destroy
    redirect_to screenings_path
  end

  def screening_params
    params.require(:screening).permit(:hall_id, :movie_id, :start_time)
  end

  def set_screening
    @screening = Screening.find(params[:id])
  end
end

app/helpers/screenings_helper.rb
# frozen_string_literal: true

module ScreeningsHelper
end

app/views/screenings/_form.html.erb
 <%= render 'shared/errors', obj: @screening %>
<%= form_with(model: @screening, data: { turbo: false }, local: true) do |f|%>
  <div class="row mb-6">
    <%= f.label :movie_id, "Movie:", class: "col-sm-2 col-form-label" %>
  </div>
  <div class="col-sm-10">
    <%= f.collection_select :movie_id, Movie.order(:title), :id, :title, class: "form-control" %>
  </div>
  <div class="row mb-6">
    <%= f.label :hall_id, "Hall:", class: "col-sm-2 col-form-label" %>
  </div>
  <div class="col-sm-10">
    <%= f.collection_select :hall_id, Hall.order(:id), :id, :name, class: "form-control" %>
  </div>
  <div class="row mb-6">
    <%= f.label :start_time, "Start time:", class: "col-sm-2 col-form-label" %>
  </div>
  <div class="col-sm-10">
    <%= f.datetime_field :start_time, class: "form-control" %>
  </div>
  <div class = "mt-3">
    <%= f.submit class: "btn btn-outline-light btn-lg" %>
  </div>
<%end%>

app/views/screenings/edit.html.erb
<%= render 'form', screening: @screening%>

app/views/screenings/index.html.erb
 <% movies.each do |movie| %>
  <%if movie.screenings.any?%>
    <div class="movie">
      <h2><%= link_to movie.title, movie_path(movie)%></h2>
      <p><%= "#{movie.duration} min." %></p>
      <%movie.screenings.each do |screening|%>
        <%= button_to "#{screening.start_time.strftime("%d/%m/%Y %H:%M")}", movie_screening_path(movie.id, screening), method: :get%>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/screenings/new.html.erb
<%= render 'form', screening: @screening%>

app/views/screenings/show.html.erb
<h2><%= @screening.movie.title %></h2>
<%= "#{@screening.start_time.strftime("%d/%m/%Y %H:%M")}" %>
<p><%= "Hall #{@screening.hall.name}" %></p>
<%= button_to "Choose seats", new_screening_reservation_path(@screening), method: :get%>
<% if user_signed_in? && policy(@screening).update? %>
  <div class ="mt-3">
    <%= button_to 'Edit Screening', edit_screening_path(@screening), class: "btn btn-secondary mb-3", method: :get%>
    <%= button_to 'Delete Screening', @screening,  method: :delete, class: "btn btn-danger mb-3"%>
  </div>
<% end %>