config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'
  root 'pages#home'
  resources :movies do
    resources :screenings, only: [:show]
  end

  resources :screenings do
    resources :reservations, only: %i[new create]
  end
  resources :reservations, only: %i[index show update destroy]

  get '/user', to: 'users#show'

  post 'screenings/:screening_id/reservations/offline', to: 'reservations#create_at_desk', as: 'offline_reservation'

  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
      resources :movies, only: %i[index show]

      resources :screenings, only: %i[show] do
        resources :reservations, only: %i[create]

        post '/reservations', to: 'reservations#create'
      end
      resources :reservations, only: %i[show]
    end
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :screening
  belongs_to :user, optional: true
  has_many :tickets
  validates :status, presence: true
  enum :status, { booked: 0, cancelled: 1, accepted: 2 }
  validate :validate_reservation, on: :create

  def screening
    Screening.with_deleted.find(screening_id)
  end

  def validate_reservation
    errors.add(:base, message: 'Choose at least one seat') if seats.compact_blank.blank?
    errors.add(:base, message: 'Seat(s) taken') if !seats.compact_blank.blank? && seat_taken?(screening, seats)
  end

  def seat_taken?(screening, seats)
    seats.each do |seat|
      return true unless screening.available_seats.include? seat
    end
    false
  end

  def seats
    tickets.map(&:seat)
  end
end

app/controllers/api/v1/reservations_controller.rb
module Api
  module V1
    class ReservationsController < ApiController
      before_action :authenticate_user!

      def create
        @reservation = Reservations::UseCases::Create.new(
          screening_id: params[:screening_id],
          user_id: current_user.id,
          seats: params.dig(:reservations, :seats),
          status: :booked
        ).call
        if @reservation.errors.none?
          ConfirmationMailJob.perform_later(@reservation.id)
          render json: ReservationSerializer.new(@reservation, include: include_options, fields: fields_options),
                 status: :created
        else
          render json: @reservation.errors, status: :unprocessable_entity
        end
      end

      def show
        @reservation = Reservations::UseCases::Find.new(id: params[:id]).call
        render json: ReservationSerializer.new(@reservation, include: include_options, fields: fields_options)
      end

      def include_options
        %i[user tickets screening.movie screening.hall]
      end

      def fields_options
        {
          user: [:email],
          tickets: [:seat],
          screening: %i[start_time movie hall],
          movie: %i[title duration],
          hall: [:name]
        }
      end
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  include Pundit::Authorization
  before_action :set_screening, only: %i[new create create_at_desk]
  before_action :authenticate_user!
  def new
    authorize Reservation
    @reservation = Reservation.new
  end

  def create
    authorize Reservation
    @reservation = Reservations::UseCases::Create.new(screening_id: params[:screening_id], user_id: current_user.id,
                                                      seats: params[:seats], status: :booked).call
    if @reservation.errors.any?
      render :new, status: :unprocessable_entity
    else
      ConfirmationMailJob.perform_later(@reservation.id)
      redirect_to reservation_path(@reservation)
    end
  end

  def create_at_desk
    authorize Reservation
    @reservation = Reservations::UseCases::CreateAtDesk.new(screening_id: params[:screening_id],
                                                            seats: params[:seats], status: :accepted).call
    if @reservation.errors.any?
      render :new, status: :unprocessable_entity
    else
      redirect_to reservation_path(@reservation)
    end
  end

  def update
    @reservation = Reservations::UseCases::Find.new(id: params[:id]).call
    authorize @reservation
    @reservation = Reservations::UseCases::Update.new(id: params[:id], status: params[:status]).call
    redirect_to reservation_path(@reservation)
  end

  def destroy
    @reservation = Reservations::UseCases::Find.new(id: params[:id]).call
    authorize @reservation
    @reservation = Reservations::UseCases::Cancel.new(id: params[:id]).call
    CancellationMailJob.perform_later(@reservation.id)
    redirect_to reservation_path(@reservation)
  end

  def show
    @reservation = Reservations::UseCases::Find.new(id: params[:id]).call
    authorize @reservation
  end

  def index
    @reservations = policy_scope(Reservation)
    @pagy, @reservations = pagy(@reservations.order(created_at: :desc))
  end

  private

  def set_screening
    @screening = Screening.find(params[:screening_id])
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/index.html.erb
<%== pagy_bootstrap_nav(@pagy) %>
<% @reservations.each do |reservation| %>
  <div class="card">
    <div class="card-header">
      <h5 class="card-title"><%= "Reservation no. #{reservation.id}" %> <span class="badge bg-secondary"><%= "status: #{reservation.status}"%></span></h5>
      <% if reservation.user_id.present?%>
        <p class="card-text"><%= "User: #{reservation.user.email}"%></p>
      <% end %>
    </div>
    <div class="card-body">
      <h2><%= reservation.screening.movie.title %></h2>
      <p class="card-text"> <%= "#{reservation.screening.start_time.strftime("%d/%m/%Y %H:%M")}" %></p>
      <p class="card-text"><%= "Hall #{reservation.screening.hall.name}" %></p>
    </div>
    <%= button_to "Show reservation", reservation_path(reservation), method: :get%>
  <%end%>

app/views/reservations/new.html.erb
 <%= render 'shared/errors', obj: @reservation %>
<h2><%= @screening.movie.title %></h2>
<%= "#{@screening.start_time.strftime("%d/%m/%Y %H:%M")}" %>
<p><%= "Hall #{@screening.hall.name}" %></p>
<%= form_with(url: screening_reservations_path, method: "post") do |f|%>
  <% @screening.hall.seats.each do |seat| %>
    <div class="form-check form-check-inline">
      <%= f.check_box :seats, { multiple: true, class: "form-check-input", 
      disabled: (!@screening.available_seats.include?(seat) ), checked: false}, seat, false %>
      <%= f.label :seats, seat, class: "form-check-label"%>
    </div>
  <% end %>
  <div class = "form-group justify-content-center d-block p-3 m-3">
    <% if current_user.user? %>
      <%= f.submit 'Book a reservation', class: "btn btn-outline-light btn-lg" %>
    <%end%>
    <% if policy(@reservation).create_at_desk? %>
      <%= f.submit 'Book offline reservation', formaction: offline_reservation_path, class: "btn btn-outline-light btn-lg" %>
    <%end%>
  </div>
<% end %>

app/views/reservations/show.html.erb
<div class="card">
  <div class="card-header">
    <h5 class="card-title"><%= "Reservation no. #{@reservation.id}" %> <span class="badge bg-secondary"><%= "status: #{@reservation.status}"%></span></h5>
  </div>
  <div class="card-body">
    <h2><%= @reservation.screening.movie.title %></h2>
    <p class="card-text"> <%= "#{@reservation.screening.start_time.strftime("%d/%m/%Y %H:%M")}" %></p>
    <p class="card-text"><%= "Hall #{@reservation.screening.hall.name}" %></p>
    <% @reservation.tickets.each_with_index do |t, i|%>
      <h4 class="card-text"><%= "Ticket #{i +1}" %></h4>
      <p class="card-text"><%= "Seat #{t.seat}" %></p>
      <p class="card-text"><%= "Ticket id: #{t.id}" %></p>
    <%end%>
    <%if @reservation.booked?%>
      <%if policy(@reservation).update?%>
        <%= form_with(url: reservation_path, method: "put") do |f|%>
          <%= f.button  "Accept", type: 'submit', name: 'status', value: "accepted", class: "btn btn-outline-success btn-lg" %>
        <%end%>
        <%= form_with(url: reservation_path, method: "delete") do |f|%>
          <%= f.button  "Cancel", type: 'submit', name: 'status', value: "cancelled", class: "btn btn-outline-warning btn-lg", method: :delete%>
        <%end%>
      <%else%>
        <%= form_with(url: reservation_path, method: "delete") do |f|%>
          <%= f.button  "Cancel", type: 'submit', name: 'status', value: "cancelled", class: "btn btn-outline-warning btn-lg", method: :delete%>
        <%end%>
      <%end%>
    <%end%>
  </div>
</div>