config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'
  root 'pages#home'
  resources :movies do
    resources :screenings, only: [:show]
  end

  resources :screenings do
    resources :reservations, only: %i[new create]
  end
  resources :reservations, only: %i[index show update destroy]

  get '/user', to: 'users#show'

  post 'screenings/:screening_id/reservations/offline', to: 'reservations#create_at_desk', as: 'offline_reservation'

  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
      resources :movies, only: %i[index show]

      resources :screenings, only: %i[show] do
        resources :reservations, only: %i[create]

        post '/reservations', to: 'reservations#create'
      end
      resources :reservations, only: %i[show]
    end
  end
end

app/views/layouts/_messages.html.erb
  <% flash.each do |name, msg| %>
  <% if flash[:alert] %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= msg %>
    <% else %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= msg %>
      <% end %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "MONTE CINEMA", root_path, class: "navbar-brand  fw-bolder text-body ", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-success fw-bold" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Profile [<%= current_user.email %>]
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li class="nav-item">
                <% if !current_user.user?%>
                  <%= link_to "All reservations", reservations_path(), class: "nav-link text-body" %>
                </li>
              <%else%>
                <li class="nav-item">
                  <%= link_to "My reservations", reservations_path(), class: "nav-link text-body" %>
                </li>
              <% end %>
            </ul>
          </li>
          <% if !current_user.user?%>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-body fw-bold" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Movies
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li class="nav-item">
                  <%= link_to "Add movie", new_movie_path(), class: "nav-link text-body" %>
                </li>
                <li class="nav-item">
                  <%= link_to "All movies", movies_path(), class: "nav-link text-body" %>
                </li>
              </ul>
            </li>
          <% end %>
          <% if !current_user.user?%>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-body fw-bold" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Screenings
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li class="nav-item">
                  <%= link_to "Add screening", new_screening_path(), class: "nav-link text-body" %>
                </li>
                <li class="nav-item">
                  <%= link_to "All screenings", screenings_path(), class: "nav-link text-body" %>
                </li>
              </ul>
            </li>
          <%end %>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', destroy_user_session_path, class: "nav-link fw-bold text-body ",  data: { "turbo-method": :delete} %>
        </li>
        <% if !user_signed_in? || current_user.user?%>
          <li class="nav-item">
            <%= link_to 'Screenings',  screenings_path, class: "nav-link fw-bold text-body" %>
          </li>
        <%end%>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in',  new_user_session_path, class: "nav-link fw-bold text-success" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up',  new_user_registration_path, class: "nav-link fw-bold text-body" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Screenings',  screenings_path, class: "nav-link fw-bold text-body" %>
        </li>
      <% end %>
    </ul>
  </li>
</ul>
</div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MonteCinema</title>
    <link href="https://fonts.googleapis.com/css2?family=Eczar:wght@500;600&family=Roboto+Mono:wght@200;300;400;500;600&family=Roboto:wght@300&display=swap" rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/navigation'%>
    <%= render 'layouts/messages' %>
    <div class="px-4 py-5 my-5  text-bg-secondary p-3">
      <%= yield %>
    </div>
  </body>
</html>